local utils = require("utils")
local map = utils.map

vim.g.mapleader = " "
map("i", "jj", [[<ESC>]])
map("t", "jj", [[<C-\><C-n>]])
map("n", "<S-h>", vim.cmd["bprev"])
map("n", "<S-l>", vim.cmd["bnext"])
map("n", "q", [[<Nop>]])
map("n", "Y", [[y$]])
map("n", "x", [["_d]])
map("n", "X", [["_D]])
map("n", "f<CR>", [[}]])
map("n", "F<CR>", [[{]])
map({ "n", "v" }, "j", [[gj]])
map({ "n", "v" }, "k", [[gk]])
map({ "n", "v" }, "M", [[%]])
map({ "n", "v" }, "<C-h>", "[(")
map({ "n", "v" }, "<C-l>", "])")
map({ "n", "v", "o" }, "<Leader>h", [[^]])
map({ "n", "v", "o" }, "<Leader>l", [[$]])
map({ "n" }, "<Leader>w", vim.cmd["w"])
map("x", "x", [["_x]])
map("o", "x", [[d]])
map("x", "y", [[mzy`z]])
map("x", "d", [[mzd`z]])
map("x", "gc", [[mzgc`z]])
