vim.opt.helplang = { "en" }
vim.opt.number = true
-- vim.opt.cursorline = true
vim.opt.cursorcolumn = true
vim.opt.signcolumn = "yes"
vim.opt.list = true
vim.opt.cmdheight = 1
vim.opt.winblend = 30
vim.opt.pumblend = 30
vim.opt.termguicolors = true
vim.opt.wildoptions = "pum"
vim.opt.laststatus = 1
vim.opt.showcmd = true
vim.opt.background = "dark"
vim.opt.ruler = true
vim.opt.showtabline = 1
vim.opt.hlsearch = true
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.incsearch = true
vim.opt.foldenable = false
vim.opt.wrap = true
vim.opt.confirm = true
vim.opt.hidden = true
vim.opt.autoread = true
vim.opt.autoindent = true
vim.opt.smartindent = true
vim.opt.clipboard = "unnamed"
vim.opt.completeopt = { "menuone", "noinsert" }
vim.opt.wildmenu = true
vim.opt.timeout = true
vim.opt.timeoutlen = 300
-- vim.opt.autochdir = true
