[[plugins]]
repo = 'Shougo/ddu.vim'
depends = 'denops.vim'
hooks_file = '$BASE_DIR/hooks/ddu.lua'


[[plugins]]
repo = 'Shougo/ddu-commands.vim'
depends = 'ddu.vim'


# source

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'


[[plugins]]
repo = 'Shougo/ddu-source-file'


[[plugins]]
repo = 'Shougo/ddu-source-action'


[[plugins]]
repo = 'kamecha/ddu-source-window'


[[plugins]]
repo = 'tennashi/ddu-source-git'


[[plugins]]
repo = '4513ECHO/ddu-source-source'


# filter

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'


[[plugins]]
repo = 'Shougo/ddu-filter-sorter_alpha'


[[plugins]]
repo = 'Shougo/ddu-filter-sorter_reversed'


[[plugins]]
repo = 'uga-rosa/ddu-filter-converter_devicon'


[[plugins]]
repo = 'staticWagomU/ddu-filter-matcher_specific_items'


# kind

[[plugins]]
repo = 'Shougo/ddu-kind-file'


# ui

[[plugins]]
repo = 'Shougo/ddu-ui-ff'


[[plugins]]
repo = 'Shougo/ddu-ui-filer'


# column

[[plugins]]
repo = 'Shougo/ddu-column-filename'


[[plugins]]
repo = 'kamecha/ddu-column-custom'
