[[plugins]]
repo = 'echasnovski/mini.bufremove'
on_map = ['<Leader>bd']
hooks_file = '$BASE_DIR/hooks/mini.bufremove.lua'


[[plugins]]
repo = 'echasnovski/mini.comment'
on_event = ['BufNewFile', 'BufRead']
# on_map = ['gc', 'gcc']
hooks_file = '$BASE_DIR/hooks/mini.comment.lua'


[[plugins]]
repo = 'echasnovski/mini.cursorword'
on_event = ['BufNewFile', 'BufRead']
hooks_file = '$BASE_DIR/hooks/mini.cursorword.lua'


[[plugins]]
repo = 'echasnovski/mini.jump'
on_map = { nxo = ['f', 'F', 't', 'T'] }
hooks_file = '$BASE_DIR/hooks/mini.jump.lua'


[[plugins]]
repo = 'echasnovski/mini.notify'
lazy = false
hooks_file = '$BASE_DIR/hooks/mini.notify.lua'


[[plugins]]
repo = 'echasnovski/mini.starter'
lazy = false
hooks_file = '$BASE_DIR/hooks/mini.starter.lua'
