[[plugins]]
repo = 'vim-skk/skkeleton'
depends = 'denops.vim'
on_event = 'InsertEnter'
on_source = 'ddc.vim'
hooks_file = '$BASE_DIR/hooks/skkeleton.lua'


[[plugins]]
repo = 'delphinus/skkeleton_indicator.nvim'
on_source = 'skkeleton'
hooks_file = '$BASE_DIR/hooks/skkeleton_indicator.lua'
